### ISSUE TITLE
Does it work in the browser ?

### ISSUE THREAD

**Issue by sguimmara** [gz65555/ktx2-encoder#1]
Hello,

It's a bit unclear reading the README, is this library able to perform texture compression at runtime in the browser, or is it an offline/Node only library ?

**Comment by gz65555** [comment]
It works in browser currently. I am about to make it works in node.

**Comment by sguimmara** [comment]
Where is the source code for the WASM encoder ?

**Comment by gz65555** [comment]
@sguimmara https://github.com/BinomialLLC/basis_universal

**Comment by GitHubDragonFly** [comment]
For those who might be interested in using this directly in the browser, without node, here are some links:

- My online [IMG2MESH](https://githubdragonfly.github.io/viewers/templates/IMG2MESH.html) app is capable of processing only 1 image at the time which can be exported to KTX2 format
  - this is using the latest `0.0.0-experimental.5` version (check the code in the next link)
- `IMG2MESH` [code page](https://github.com/GitHubDragonFly/GitHubDragonFly.github.io/blob/main/viewers/templates/IMG2MESH.html) where you can search for term `ktx2-encoder` to see all sections where it is used

My question for @gz65555 would be about the `web` folder missing from the `dist` folder in the latest version on NPM - was this omitted for some specific reason?

**Comment by sguimmara** [comment]
For some reason the `web` folder is missing from the NPM package in version 0.1.1, i.e the content of the package does not match what is advertised in the `package.json` file:

![image](https://github.com/user-attachments/assets/5747de73-9de3-48b9-89d9-7181da7746d0)

![image](https://github.com/user-attachments/assets/6d281d5c-ed66-4745-8ce5-6732b28e0872)

**Comment by GitHubDragonFly** [comment]
This JS library seems to be unique on the web so kudos to @gz65555 for creating it.

Since the last experimental version `0.0.0-experimental.5` is still functional for importing via `esm.sh` then I have no issues with it.

**Comment by gz65555** [comment]
Thanks for pointing out this issue. It has been fixed in version [0.1.1](https://www.npmjs.com/package/ktx2-encoder?activeTab=code).

**Comment by GitHubDragonFly** [comment]
Cool, it seems to be working fine at least in my apps.

I guess it would be up to one of you two guys to decide when to eventually close this issue.
