### ISSUE TITLE
Add option to set the URLs to remote resources

### ISSUE THREAD

**Issue by sguimmara** [gz65555/ktx2-encoder#6]
Currently, the path to the encoder JS and WASM files are [hardcoded](https://github.com/gz65555/ktx2-encoder/blob/main/src/web/BrowserBasisEncoder.ts#L19):

https://github.com/gz65555/ktx2-encoder/blob/f6d2d53b7b6c4cebb99e1277fe29290aded384c4/src/web/BrowserBasisEncoder.ts#L19

It would be great to be able to specify the path to those files.

**Comment by gz65555** [comment]
Good idea, i'll make it an option.

**Comment by gz65555** [comment]
I have released 0.2.0 version, you can use `jsUrl` and `wasmUrl` options to specify your custom urls.
